### ISSUE TITLE
notifyDataSetChanged Issue

### ISSUE THREAD

**Issue by NazarAbbas** [frankiesardo/LinearListView#12]
Hi. I'm facing a big issue I have more data to bind LinearListView,but when use notifyDataSetChanged then it takes lot of time, how can I remove this issue?

Thanks

**Comment by frankiesardo** [comment]
LinearListView is not optimised for big amount of data. I suggest you use another layout (like RecyclerView)

**Comment by NazarAbbas** [comment]
First of all thanks for reply, I need your help. I'm using EditText in ListView when I click on EditText to editing some data then it lost focus, can you guide me how to handle EditText in listview? Or if possible please create a demo on github it will be very helpfull for developers.

Thanks in advance.
